#! /bin/bash

#set -e
spinner=('\' '|' '/' '-')

killer(){
    spin &
    pid=$!

    for i in `echo {1..10}`
    do
        sleep 1
    done

    kill $pid
}

spin() {
    echo -ne ""
    while true
    do
        for s in ${spinner[@]}
        do
            echo -ne "\b${s}"
            sleep 0.5
        done	 
    done
}

#A function for finding the packageManager of the distro
findPackageManager(){
	declare -A osInfo;
	osInfo[/etc/redhat-release]=yum
	osInfo[/etc/arch-release]=pacman
	osInfo[/etc/debian_version]=apt-get
	osInfo[/etc/alpine-release]=apk

	for f in ${!osInfo[@]}
	do
	    if [[ -f $f ]];then
	        echo ${osInfo[$f]}
	    fi
	done
}

#A function for checking whether or not python is existed
isPythonExist(){
	python --version

	if [ $? -eq 0 ];then
		: # Passing
	else
		packageManager=$(findPackageManager)
		if [ $packageManager == "yum" ];then
			sudo yum install -y python3
		elif [ $packageManager == "pacman" ];then
			sudo Pacman -S python3
		elif [ $packageManager == "apt-get" ];then
			sudo apt-get -y install python3
		elif [ $packageManager == "apk" ];then
			sudo apk add python3
		fi
	fi

	clear
}



# A function for checking whether or not youtube-dl is existed
isYotubeDlExist(){
	youtube-dl --version

	if [ $? -eq 0 ];then
		local returned='yes'
		echo ${returned}
	else
		local returned='no'
		echo ${returned}
	fi

}



# A function for scrapping YouTube
scrap(){
	echo -n "Yoo ` uname -n `, Type playlist for a playlist or single for a single video: "
	read typeOfVideo
	if [ $typeOfVideo == 'playlist' ];then
		echo -n "Please enter the playlist url that you went to download? "
		read Url
		echo -n "Scrapping youtube: "
		killer
		youtube-dl -i -f mp4 --yes-playlist $Url
	else
		echo -n "Please enter the video url that you went to download? "
		read Url
		echo -n "Scrapping youtube: "
		killer
		youtube-dl $Url

	fi


}

#Our Function for scrapping video
scrapVideo(){

	# Storing the returned value of the isYotubeDlExist function inside a variable called YoutubeDlIsThere
	YouTubeDlIsThere=$(isYotubeDlExist)

	# Checking if the returned value contains the word 'yes'
	if [[ $YouTubeDlIsThere =~ "yes" ]]; then
		scrap
	else
		isPythonExist
		echo
		echo "Hey `uname -n `, Our program is installing Youtube-dl into your machine so please hit CTRL + C if you want to quit the process! "
		sleep 1
		pip install youtube-dl
		echo
		echo "Congrats Youtube-dl is succssfully installed on your machine! "
		sleep .5
		scrapVideo

	fi

}


scrapVideo